export  const INCREASE='INCREASE';
export  const DECREASE='DECREASE';
export  const FETCHGETDATA='FETCHGETDATA';
export  const FETCHGETDATA_SUCCESS='FETCHGETDATA_SUCCESS';
export  const FETCHGETDATA_ERROR='FETCHGETDATA_ERROR';
export  const CLEARFETCHDATA='CLEARFETCHDATA';

